name: macos

on:
  pull_request:
    branches:
    - main

jobs:
  macos-x64:
    runs-on: macos-13
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build Debug
        run: |
          $GITHUB_WORKSPACE/./build_macos_x64_debug.sh
      - name: Run tests
        run: |
          ninja test -C $GITHUB_WORKSPACE/build/Debug/
  # macos-arm:
  #   runs-on: macos-latest